;  ascii.inc
;
;  ASCII constants
;
;  Paul Griffiths, March 21, 2015

CHAR_NUL        equ     0x00            ;  ASCII null character
CHAR_BS         equ     0x08            ;  ASCII backspace character
CHAR_HTAB       equ     0x09            ;  ASCII horizontal tab character
CHAR_TAB        equ     0x09            ;  ASCII horizontal tab character
CHAR_LF         equ     0x0a            ;  ASCII line feed character
CHAR_VTAB       equ     0x0b            ;  ASCII vertical tab character
CHAR_FF         equ     0x0c            ;  ASCII form feed character
CHAR_CR         equ     0x0d            ;  ASCII carriage return character
CHAR_SPACE      equ     0x20            ;  ASCII space character
CHAR_ZERO       equ     0x30            ;  ASCII code for '0'
CHAR_NINE       equ     0x39            ;  ASCII code for '9'
CHAR_UPPER_A    equ     0x41            ;  ASCII uppercase 'A'
CHAR_UPPER_Z    equ     0x5a            ;  ASCII uppercase 'Z'
CHAR_LOWER_A    equ     0x61            ;  ASCII lowercase 'a'
CHAR_LOWER_Z    equ     0x7a            ;  ASCII lowercase 'b'
